#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "Usage: key-gen [-f] <name>"
    echo "Options:"
    echo "  -f     Force overwrite of existing files"
    exit 1
fi

force=false
while getopts "f" opt; do
  case $opt in
    f) force=true ;;
    \?) >&2 echo "Invalid option: -$OPTARG"
        exit 1 ;;
  esac
done

shift $((OPTIND - 1))

if [ -z "$1" ]; then
    >&2 echo "Expected name as argument"
    exit 1
fi

vkey="$KEYS_PATH/$1.vkey"
skey="$KEYS_PATH/$1.skey"
addr="$ADDR_PATH/$1.addr"

check_file() {
  local file=$1
  if [ -f "$file" ]; then
    if [ "$force" = true ]; then
      rm "$file"
    else
      read -p "$2 file '$file' already exists. Do you want to overwrite it? [Y/N]: " response
      case $response in
        [Yy]* ) rm "$file";;
        [Nn]* ) exit 1;;
        * ) >&2 echo "Invalid response. Please enter Y or N."
            check_file $file $2;;
      esac
    fi
  fi
}

check_file "$vkey" "Verification key"
check_file "$skey" "Signing key"
check_file "$addr" "Address"

cardano-cli address key-gen \
--verification-key-file $vkey \
--signing-key-file $skey

cardano-cli address build \
--payment-verification-key-file $vkey \
--out-file $addr

if [ $? -eq 0 ]; then
  echo "Wrote verification key for $1 to '$vkey'"
  echo "Wrote signing key for $1 to '$skey'"
  echo "Wrote address for $1 to '$addr'"
fi