#!/usr/bin/env bash

while getopts ":n:p:" opt; do
  case $opt in
    n)
      if [ -z "${OPTARG}" ]; then
        >&2 echo "error: missing script name argument"
        exit 1
      fi
      scripts_path=$NATIVE_SCRIPTS_PATH
      script_name=$OPTARG
      file_ext="script"
      ;;
    p)
      if [ -z "${OPTARG}" ]; then
        >&2 echo "error: missing script name argument"
        exit 1
      fi
      scripts_path="$PLUTUS_SCRIPTS_PATH"
      script_name=$OPTARG
      file_ext="plutus"
      ;;
    \?)
      >&2 echo "Usage: policyid [-n FILENAME] [-p FILENAME]"
      exit 1
      ;;
    :)
      >&2 echo "option -$OPTARG requires an argument"
      exit 1
      ;;
  esac
done

if [ -z "$script_name" ]; then
  >&2 echo "Usage: policyid [-n FILENAME] [-p FILENAME]"
  >&2 echo "Options:"
  >&2 echo "  -n     Native script"
  >&2 echo "  -p     Plutus script"
  exit 1
fi

cardano-cli transaction policyid \
--script-file $scripts_path/$script_name.$file_ext