#!/usr/bin/env bash

while getopts ":n:p:" opt; do
  case $opt in
    n)
      if [ -z "${OPTARG}" ]; then
        >&2 echo "error: missing script name argument"
        exit 1
      fi
      scripts_path=$NATIVE_SCRIPTS_PATH
      script_name=$OPTARG
      file_ext="script"
      ;;
    p)
      if [ -z "${OPTARG}" ]; then
        >&2 echo "error: missing script name argument"
        exit 1
      fi
      scripts_path="$PLUTUS_SCRIPTS_PATH"
      script_name=$OPTARG
      file_ext="plutus"
      ;;
    \?)
      >&2 echo "Usage: script-addr [-n FILENAME] [-p FILENAME]"
      exit 1
      ;;
    :)
      >&2 echo "option -$OPTARG requires an argument"
      exit 1
      ;;
  esac
done

if [ -z "$script_name" ]; then
  >&2 echo "Usage: script-addr [-n FILENAME] [-p FILENAME]"
  exit 1
fi

addr=$ADDR_PATH/$script_name.addr

if [ -f "$addr" ]; then
  read -p "Address file '$addr' already exists. Do you want to overwrite it? [Y/N]: " response
  case $response in
    [Yy]* ) rm "$addr";;
    [Nn]* ) exit 1;;
    * ) >&2 echo "Invalid response. Please enter Y or N."
        exit 1;;
  esac
fi

cardano-cli address build \
--payment-script-file $scripts_path/$script_name.$file_ext \
--out-file $addr

if [ $? -eq 0 ]; then
  echo "Wrote script address to '$addr'"
fi