#!/usr/bin/env bash

function usage {
    echo "Usage: $0 [-n|-p] POLICY_NAME TOKEN_NAME"
    echo "  -n: Native script"
    echo "  -p: Plutus script"
    exit 1
}

# Check for the number of arguments
if [ $# -ne 3 ]; then
    usage
fi

# Parse command-line options
while getopts ":np" opt; do
    case $opt in
        n)
            script_type="n"
            ;;
        p)
            script_type="p"
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            usage
            ;;
    esac
done

# Shift the parsed options out of the argument list
shift $((OPTIND - 1))
# Assign arguments
policy_name="$1"
token_name="$2"

policy_id=$(policyid "-$script_type" "$policy_name" 2>&1)

# Continue only if policyid script succeeded:
if [ $? -ne 0 ]; then
    echo "$policy_id"
    exit 1
fi

echo -n $policy_id.$(token-name $token_name)