#!/usr/bin/env bash

if [ -z "$1" ]; then
    >&2 echo "expected transaction name as argument"
    exit 1
fi

cardano-cli transaction submit \
--tx-file "$TX_PATH/$1.signed"

if [ $? -eq 0 ]; then
  cexplorer_url="cexplorer.io/tx/$(tx-hash $1)"
  echo -e "View transaction:\n"
  if [[ $CARDANO_NETWORK = "mainnet" ]]; then
    echo -e "\thttps://$cexplorer_url"
  else
    echo -e "\thttps://$CARDANO_NETWORK.$cexplorer_url"
  fi
fi